package dev.traveler.core.debug;

public enum DebugAnomaly {
    NO_NAVIGATION,
    NO_PATH,
    PATH_NOT_FOUND,
    STALE_NAVIGATION_DEBUG,
    NO_MOVEMENT_KEYS_WHILE_ACTIVE,
    TARGET_BEHIND_PLAYER,
    CAMERA_YAW_LAG_HIGH,
    ZERO_VECTOR_WHILE_NOT_COMPLETED,
    JUMP_REQUESTED_WITHOUT_SPACE,
    SPECIAL_ACTION_BLOCKED,
    LOW_SPEED_FAR_FROM_TARGET
}
